apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: r-mlflow-model-regression
  namespace: seldon
spec:
  name: rmodel-deploy-regression
  predictors:
  - name: default
    replicas: 1
    graph:
      name: rmodel
      type: MODEL
      endpoint:
        type: REST
    componentSpecs:
    - spec:
        containers:
        - name: rmodel
          image: yashbaviskar/boston-rmodel-api:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          env:
          - name: MLFLOW_TRACKING_URI
            value: "http://172.26.95.101:5000"
          - name: MLFLOW_S3_ENDPOINT_URL
            value: "http://172.26.95.101:8001"
          - name: AWS_ACCESS_KEY_ID
            value: "admin"
          - name: AWS_SECRET_ACCESS_KEY
            value: "admin123"
          - name: MODEL_URI
            value: "s3://mlflow-artifacts/9/6ee2a932beb84a3b875694a36af388a1/artifacts/model"


