apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: ghcr.io/mlflow/mlflow:v2.14.0
        command: ["/bin/sh", "-c"]
        args:
          - |
            pip install boto3 && \
            mlflow server \
            --host 0.0.0.0 \
            --port 5000 \
            --backend-store-uri sqlite:///mlflow.db \
            --default-artifact-root s3://mlflow-artifacts
        ports:
        - containerPort: 5000
        env:
        - name: MLFLOW_SERVER_HOST
          value: "0.0.0.0"
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"
        - name: AWS_S3_ENDPOINT_URL
          value: "http://minio-service:9000"
        - name: MLFLOW_S3_ENDPOINT_URL
          value: "http://minio-service:9000"
        - name: MLFLOW_S3_IGNORE_TLS
          value: "true"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: mlops-secrets
              key: access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: mlops-secrets
              key: secret-key

---

apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
spec:
  type: ClusterIP
  selector:
    app: mlflow
  ports:
    - port: 5000
      targetPort: 5000
